// src/types/enums.ts
// All system enums — single source of truth

export enum UserStatus {
  INACTIVE = 'INACTIVE',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  TEAM_LEADER = 'TEAM_LEADER',
  INVESTOR = 'INVESTOR',
}

export enum TransactionType {
  REGISTRATION_FEE = 'REGISTRATION_FEE',
  WALLET_TOPUP = 'WALLET_TOPUP',
  INVESTMENT_DEBIT = 'INVESTMENT_DEBIT',
  PROFIT_CREDIT = 'PROFIT_CREDIT',
  WITHDRAWAL = 'WITHDRAWAL',
  REFUND = 'REFUND',
  ADMIN_CREDIT = 'ADMIN_CREDIT',
  ADMIN_DEBIT = 'ADMIN_DEBIT',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum ProjectStatus {
  PLANNED = 'PLANNED',
  LAND_ACQUIRED = 'LAND_ACQUIRED',
  LEGAL_IN_PROGRESS = 'LEGAL_IN_PROGRESS',
  APPROVED = 'APPROVED',
  UNDER_DEVELOPMENT = 'UNDER_DEVELOPMENT',
  READY_FOR_SALE = 'READY_FOR_SALE',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
}

export enum PlotStatus {
  AVAILABLE = 'AVAILABLE',
  HELD = 'HELD',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
}

export enum PlotType {
  CORNER = 'CORNER',
  MIDDLE = 'MIDDLE',
  DOUBLE_ROAD = 'DOUBLE_ROAD',
}

export enum SalePaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
}

export enum HoldStatus {
  ACTIVE = 'ACTIVE',
  RELEASED_MANUAL = 'RELEASED_MANUAL',
  RELEASED_EXPIRED = 'RELEASED_EXPIRED',
  RELEASED_ADMIN = 'RELEASED_ADMIN',
  CONVERTED_TO_SALE = 'CONVERTED_TO_SALE',
}

export enum DistributionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ROLLED_BACK = 'ROLLED_BACK',
}

export type AuditEventType =
  | 'USER_REGISTERED'
  | 'USER_LOGIN_SUCCESS'
  | 'USER_LOGIN_FAILURE'
  | 'USER_LOGOUT'
  | 'PASSWORD_CHANGED'
  | 'PASSWORD_RESET_REQUESTED'
  | 'MFA_ENABLED'
  | 'MFA_DISABLED'
  | 'SESSION_REVOKED'
  | 'WALLET_TOPUP_INITIATED'
  | 'WALLET_TOPUP_COMPLETED'
  | 'INVESTMENT_CREATED'
  | 'PLOT_HELD'
  | 'PLOT_HOLD_RELEASED'
  | 'PROFIT_DISTRIBUTED'
  | 'SALE_INITIATED'
  | 'SALE_CONFIRMED'
  | 'USER_ROLE_CHANGED'
  | 'SYSTEM_CONFIG_CHANGED'
  | 'ADMIN_MANUAL_WALLET_CREDIT'
  | 'RATE_LIMIT_BREACH'
  | 'UNAUTHORIZED_ACCESS_ATTEMPT'
  | 'WEBHOOK_SIGNATURE_FAILURE';
